name: flutter_tdd_starter
description: A Very Good Project created by Very Good CLI.
version: 1.0.3+3
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.1.0
  connectivity_plus: ^1.1.0
  dartz: ^0.10.0
  device_info_plus: ^2.1.0
  device_preview:
    git:
      url: git://github.com/Husssam12/flutter_device_preview.git
      path: device_preview
  dio: ^4.0.0
  equatable: ^2.0.3
  firebase_analytics: ^8.3.2
  firebase_core: ^1.6.0
  firebase_core_platform_interface: ^4.0.1
  firebase_messaging: ^10.0.7
  firebase_messaging_web: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_iconly: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^8.2.0
  flutter_localizations:
    sdk: flutter
  flutter_sheet_localization: ^5.1.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.22.0
  form_field_validator: ^1.1.0
  get: ^4.3.8
  get_it: ^7.2.0
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  json_annotation: ^4.1.0
  lottie: ^1.1.0
  rxdart: ^0.27.2
  sentry_flutter: ^6.0.0
  shared_preferences: ^2.0.7

dev_dependencies:
  bloc_test: ^8.1.0
  build_runner: ^2.1.2
  cached_network_image: ^3.1.0
  flutter_driver: 
    sdk: flutter
    version: ^0.0.0
  flutter_sheet_localization_generator: ^5.1.7
  flutter_test:
    sdk: flutter
  integration_test: 
    sdk: flutter
  json_serializable: ^5.0.0
  mockito: ^5.0.15
  mocktail: ^0.1.4
  plugin_platform_interface: ^2.0.1
  very_good_analysis: ^2.3.0

dependency_overrides:
  analyzer: ^2.2.0
  meta: ^1.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
    - assets/svg/
