name: flutter_tdd_starter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.1.0
  connectivity_plus: ^1.1.0
  dartz: ^0.10.0
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_localizations:
    sdk: flutter
  get: ^4.3.8
  get_it: ^7.2.0
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  json_annotation: ^4.1.0
  lottie: ^1.1.0
  shared_preferences: ^2.0.7

dependency_overrides:
  analyzer: ^2.2.0
  meta: ^1.7.0
  provider: ^6.0.0

dev_dependencies:
  bloc_test: ^8.1.0
  build_runner: ^2.1.2
  device_preview: ^0.7.4
  flutter_test:
    sdk: flutter
  json_serializable: ^5.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/lotties/
