// Mocks generated by Mockito 5.0.15 from annotations
// in flutter_tdd_starter/test/features/auth/presentation/bloc/auth_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_tdd_starter/core/error/failures.dart' as _i5;
import 'package:flutter_tdd_starter/features/auth/domain/entities/request/login_body.dart'
    as _i7;
import 'package:flutter_tdd_starter/features/auth/domain/entities/response/login_entity.dart'
    as _i6;
import 'package:flutter_tdd_starter/features/auth/domain/usecases/login_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [LoginUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUsecase extends _i1.Mock implements _i3.LoginUsecase {
  MockLoginUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.LoginEntity>> call(
          _i7.LoginBody? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
          returnValue: Future<_i2.Either<_i5.Failure, _i6.LoginEntity>>.value(
              _FakeEither_0<_i5.Failure, _i6.LoginEntity>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i6.LoginEntity>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.LoginEntity>> execute(
          _i7.LoginBody? params) =>
      (super.noSuchMethod(Invocation.method(#execute, [params]),
          returnValue: Future<_i2.Either<_i5.Failure, _i6.LoginEntity>>.value(
              _FakeEither_0<_i5.Failure, _i6.LoginEntity>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i6.LoginEntity>>);
  @override
  String toString() => super.toString();
}
