// Mocks generated by Mockito 5.0.15 from annotations
// in flutter_tdd_starter/test/data/auth/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_tdd_starter/data/auth/datasources/auth_remote_data_source.dart'
    as _i3;
import 'package:flutter_tdd_starter/domain/auth/entities/entities.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeLoginEntity_0 extends _i1.Fake implements _i2.LoginEntity {}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i3.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.LoginEntity> requestLogin(_i2.LoginBody? body) =>
      (super.noSuchMethod(Invocation.method(#requestLogin, [body]),
              returnValue: Future<_i2.LoginEntity>.value(_FakeLoginEntity_0()))
          as _i4.Future<_i2.LoginEntity>);
  @override
  String toString() => super.toString();
}
